# Do not change it
version: 1

chatRadius: 100

Me:
  nickname: "AQUA"
  content: "GRAY"
  error: "RED"

Do:
  nickname: "AQUA"
  content: "GRAY"
  error: "RED"

Try:
  nickname: "AQUA"
  content: "GRAY"
  error: "RED"
  good: "GREEN"
  bad: "RED"