# Radius
# -2 - all worlds, -1 world of the sender, 0 - none, >1 - normal
# messagesOutputMode. Two types: consistent, random.

configVersion: 3

# todo: cooldowns, mutes

Expressions:
  chatRadius: 100
  message: "§6* {player} §7{message}"
  # todo permission
  list:
    ): "улыбается"
    )): "смеется"
    (: "грустит"
    ((: "сильно грустит"
    :D: "катается по полу от смеха"

Commands:
  me:
    enabled: true
    messages: ["§6* {playerName} §7{message}"]
    messagesOutputMode: "consistent"
    radius: 100
    permission: "owrp.commands.common"
  do:
    enabled: true
    messages: ["§7* {message} §6({playerName})"]
    messagesOutputMode: "consistent"
    radius: 100
    permission: "owrp.commands.common"
#  todo:
#    enabled: true
#    messages: ["пока не работает"]
#    messagesOutputMode: "consistent"
#    radius: 100
#    permission: "owrp.commands.common"
  try:
    enabled: true
    messages: ["§6* {playerName} §7{message} §c| Неудачно", "§6* {playerDisplayName} §7{message} §a| Удачно"]
    messagesOutputMode: "random"
    radius: 100
    permission: "owrp.commands.common"
  b:
    enabled: true
    messages: ["§7{playerName}: (( §r{message} §7))"]
    messagesOutputMode: "consistent"
    radius: 100
    permission: "owrp.commands.common"
  ag:
    enabled: true
    messages: ["§6{playerName}§7: §6{message}"]
    messagesOutputMode: "consistent"
    radius: -2
    permission: "owrp.commands.announce.global"
  al:
    enabled: true
    messages: ["§6{playerName}§7: §6{message}"]
    messagesOutputMode: "consistent"
    radius: 100
    permission: "owrp.commands.announce.local"

Strings:
  noPrivilege: "У вас нет привелегий для выполнения этой команды"
  errorOccurred: "Произошла ошибка"
  noConsole: "Сообщений из консоли не принимаются"
  noArgs: "Вы не ввели текст сообщения"
  pluginReload: "Плагин перезапущен"
