# Radius
# -2 - all worlds, -1 world of the sender, 0 - none, >1 - normal
# messagesOutputMode. Two types: consistent, random.

configVersion: 3

# todo: cooldowns, mutes

Expressions:
  ): "улыбается"
  )): "смеется"
  (: "грустит"
  ((: "сильно грустит"
  :D: "катается по полу от смеха"

Commands:
  me:
    enabled: true
    messages: ["§6* {player} §7{message}"]
    messagesOutputMode: "consistent"
    radius: 100
    permission: "default"
  do:
    enabled: true
    messages: ["§7* {message} §6({player})"]
    messagesOutputMode: "consistent"
    radius: 100
    permission: "default"
  todo:
    enabled: true
    messages: ["пока не работает"]
    messagesOutputMode: "consistent"
    radius: 100
    permission: "default"
  try:
    enabled: true
    messages: ["§6* {player} §7{message} §c| Неудачно", "§6* {player} §7{message} §a| Удачно"]
    messagesOutputMode: "random"
    radius: 100
    permission: "default"
  ag:
    enabled: true
    messages: ["§6{player}§7: §6{message}"]
    messagesOutputMode: "consistent"
    radius: -2
    permission: "owrp.announce.global"
  al:
    enabled: true
    messages: ["§6{player}§7: §6{message}"]
    messagesOutputMode: "consistent"
    radius: 100
    permission: "owrp.announce.local"

Strings:
  noPrivilege: "У вас нет привелегий для выполнения этой команды"
  errorOccurred: "Произошла ошибка"
  noConsole: "Сообщений из консоли не принимаются"
  noArgs: "Вы не ввели текст сообщения"
  pluginReload: "Плагин перезапущен"
