# Do not change it
version: 2

chatRadius: 100

Me:
  Color:
    nickname: "AQUA"
    content: "GRAY"
    error: "RED"
  Message:
    prefix: "* "

Do:
  Color:
    nickname: "AQUA"
    content: "GRAY"
    error: "RED"
  Message:
    prefix: "* "
    Brackets:
      open: "("
      close: ")"

Try:
  Color:
    nickname: "AQUA"
    content: "GRAY"
    error: "RED"
    good: "GREEN"
    bad: "RED"
  Message:
    prefix: "* "
    good: "| Удачно"
    bad: "| Неудачно"
