# radius:
# -2 — all worlds
# -1 — world of the sender
# 0 — none
# >1 — normal

# messagesOutputMode:
# single — First message from the list will be displayed.
# random — A random message from the list will be displayed.
# Otherwise all messages from the list will be displayed in order.

# This variable should not be changed
configVersion: 4

Expressions:
  chatRadius: 100
  message: "§6* {player} §7{message}"
  permission: "owrp.common"
  list:
    ): "улыбается"
    )): "смеется"
    (: "грустит"
    ((: "сильно грустит"
    :D: "катается по полу от смеха"

Commands:
  me:
    enabled: true
    messages: ["§6* {playerDisplayName} §7{message}"]
    radius: 100
    permission: "owrp.common"
    permissionDefault: true
  do:
    enabled: true
    messages: ["§7* {message} §6({playerDisplayName})"]
    radius: 100
    permission: "owrp.common"
    permissionDefault: true
  todo:
    enabled: false
    messages: ["пока не работает"]
    radius: 100
    permission: "owrp.common"
    permissionDefault: true
  try:
    enabled: true
    messages: ["§6* {playerDisplayName} §7{message} §c| Неудачно", "§6* {playerDisplayName} §7{message} §a| Удачно"]
    messagesOutputMode: "random"
    radius: 100
    permission: "owrp.common"
    permissionDefault: true
  b:
    enabled: true
    messages: ["§7{playerName}: (( §r{message} §7))"]
    radius: 100
    aliases: ['ooc']
    permission: "owrp.common"
    permissionDefault: true
  ag:
    enabled: true
    messages: ["§6{playerName}§7: §6{message}"]
    radius: -2
    permission: "owrp.commands.announce.global"
  al:
    enabled: true
    messages: ["§6{playerName}§7: §6{message}"]
    radius: 100
    permission: "owrp.commands.announce.local"

Strings:
  noPrivilege: "У вас нет привелегий для выполнения этой команды"
  errorOccurred: "Произошла ошибка"
  noConsole: "Сообщений из консоли не принимаются"
  noArgs: "Вы не ввели текст сообщения"
  pluginReload: "Плагин перезапущен"
